[package]
name = "cloudy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
crossterm = "0.26.1"
dirs = "5.0.0"
lazy_static = "1.4.0"
ratatui = "0.20.1"
regex = "1.7.1"
